sonar.projectKey=adamkwhite_scribe
sonar.organization=adamkwhite

sonar.projectName=scribe

sonar.sources=crates
sonar.exclusions=**/target/**,**/tests/**

sonar.tests=crates
sonar.test.inclusions=**/tests/**,**/*_test.rs

sonar.sourceEncoding=UTF-8

# Rust-specific report imports
sonar.rust.lcov.reportPaths=lcov.info
sonar.rust.clippy.reportPaths=clippy-report.json
